import org.apache.hadoop.ipc.protocolPB.RefreshCallQueueProtocolClientSideTranslatorPB;
public class FunctionUse15637 {
public void funcUse() {
RefreshCallQueueProtocolClientSideTranslatorPB refreshcallqueueprotocolclientsidetranslatorpb = new RefreshCallQueueProtocolClientSideTranslatorPB();
refreshcallqueueprotocolclientsidetranslatorpb.isMethodSupported(null);
}
}